export const langKeys = {
  // components\simpleEditModal.ts
  simple_edit_modal_save_button_title: '保存',
  // main.ts
  ribbon_button_title: '打开默认挂件侧边栏',
  cannot_create_leaf: '无法创建新的侧边栏视图',
  command_active_sidebar: '激活侧边栏',
  // settings\defaultSettings.ts
  default_widget_header_1_title: '默认标题',
  default_widget_digital_clcok_title: '数字时钟',
  default_widget_week_calendar_title: '周历',
  default_widget_time_progress_title: '时间进度',
  default_widget_donate_title: '捐赠',
  default_widget_donate_content: '如果您喜欢这个插件，请考虑捐赠支持开发者。',
  // settings\updateConfig.ts
  default_view_title: '默认视图',
  // settings\widgetEditModal.ts
  edit_widget_modal_title: '编辑小部件',
  edit_widget_modal_widget_type_desc: '小部件类型',
  edit_widget_modal_widget_title: '小部件标题',
  edit_widget_modal_widget_title_desc: '请输入小部件的标题',
  edit_widget_modal_widget_title_placeholder: '请输入标题',
  edit_widget_modal_widget_type: '小部件类型',
  edit_widget_modal_widget_custom_type: '自定义小部件类型',
  edit_widget_modal_widget_custom_type_desc: '如果您选择了自定义类型，请在此输入小部件类型名称',
  edit_widget_modal_widget_custom_type_placeholder: '请输入自定义小部件类型',
  edit_widget_modal_widget_style: '小部件样式',
  edit_widget_modal_widget_style_desc: '请选择小部件的样式',
  edit_widget_modal_widget_custom_style: '自定义小部件样式',
  edit_widget_modal_widget_custom_style_desc: '如果您选择了自定义样式，请在此输入小部件样式名称',
  edit_widget_modal_widget_custom_style_placeholder: '请输入自定义小部件样式',
  edit_widget_modal_widget_code: '小部件代码',
  edit_widget_modal_widget_code_desc: '请输入小部件的代码内容',
  edit_widget_modal_widget_code_placeholder: '请输入小部件代码',
  // settings.ts
  widget_style_title: '小部件侧边栏样式',
  widget_style_selector_title: '选择侧边栏样式',
  widget_style_selector_desc: '选择小部件侧边栏的样式',
  sidebar_list_title: '小部件侧边栏列表',
  add_sidebar_button_title: '添加新挂件侧边栏',
  new_view_title: '新挂件侧边栏',
  sidebar_edit_button_tooltip: '编辑侧边栏',
  sidebar_delete_button_tooltip: '删除侧边栏',
  delete_default_sidebar_notice: '无法删除默认侧边栏',
  delete_sidebar_button_confirm: '确认删除此侧边栏？',
  add_widget_button_title: '添加新小部件',
  move_up_button_title: '向上移动小挂件',
  move_down_button_title: '向下移动小挂件',
  edit_widget_button_title: '编辑小挂件',
  delete_widget_button_title: '删除小挂件',
  delete_widget_button_title_confirm: '确认删除此小挂件？',
  // Widget Types
  // header_1
  widget_type_header_1: '',
  widget_type_header_1_desc: '',
  // header_3
  widget_type_header_3: '',
  widget_type_header_3_desc: '',
  // digital_clock
  widget_type_digital_clock: '',
  widget_type_digital_clock_desc: '',
  // time_progress
  widget_type_time_progress: '',
  widget_type_time_progress_desc: '',
  // week_calendar
  widget_type_week_calendar: '',
  widget_type_week_calendar_desc: '',
  // month_calendar
  widget_type_month_calendar: '',
  widget_type_month_calendar_desc: '',
  // countdown_day
  widget_type_countdown_day: '',
  widget_type_countdown_day_desc: '',
  // text
  widget_type_text: '',
  widget_type_text_desc: '',
  // image
  widget_type_image: '',
  widget_type_image_desc: '',
  // quick_nav
  widget_type_quick_nav: '',
  widget_type_quick_nav_desc: '',
  // year_points
  widget_type_year_points: '',
  widget_type_year_points_desc: '',
  // file_stats
  widget_type_file_stats: '',
  widget_type_file_stats_desc: '',
  // working_time_progress
  widget_type_working_time_progress: '',
  widget_type_working_time_progress_desc: '',
  // random_notes
  widget_type_random_notes: '',
  widget_type_random_notes_desc: '',
  // battery_status
  widget_type_battery_status: '',
  widget_type_battery_status_desc: '',
  // daily_event_record
  widget_type_daily_event_record: '',
  widget_type_daily_event_record_desc: '',
  // widgets\CountdownDay.ts
  countdown_unnamed_event: '未命名事件',
  countdown_future_prefix: '距离 ',
  countdown_future_suffix: ' 还有',
  countdown_day_singular: '天',
  countdown_day_plural: '天',
  countdown_today_prefix: '今天是 ',
  countdown_today_suffix: '',
  countdown_today: '今天',
  countdown_past_prefix: '',
  countdown_past_suffix: ' 已经过去',
  // countdown_day_singular: '天',  // 重复
  // countdown_day_plural: '天',  // 重复
  // widgets\DailyEventRecord.ts
  daily_event_record_default_title: '每日事件记录',
  daily_event_record_no_note: '请在配置中指定记录笔记',
  daily_event_record_load_error: '加载记录数据失败',
  daily_event_record_today_title: '今日记录',
  daily_event_record_edit_tooltip: '编辑记录',
  daily_event_record_delete_tooltip: '删除记录',
  daily_event_record_no_records: '无记录',
  daily_event_record_add_button: '添加记录',
  daily_event_record_add_success: '记录已添加',
  daily_event_record_add_error: '添加记录失败',
  daily_event_record_edit_success: '记录已更新',
  daily_event_record_edit_error: '编辑记录失败',
  daily_event_record_invalid_time: '无效的时间格式，请使用 HH:mm 格式',
  daily_event_record_delete_confirm: '确定要删除 ${timeToDelete} 的记录吗？',
  daily_event_record_delete_success: '记录已删除',
  daily_event_record_delete_error: '删除记录失败',
  // widgets\RandomNotes.ts
  random_notes_title: '随机笔记',
  random_notes_refresh_tooltip: '刷新',
  // widgets\WorkingTimeProgress.ts
  working_time_progress_minute: '分钟',
  working_time_progress_hour: '小时',
  // working_time_progress_minute: '分钟',  // 重复
  working_time_progress_working: '工作中',
  working_time_progress_resting: '休息中',
  working_time_progress_working_is_remaining: '剩余',
};
